# Generated by Django 4.1 on 2022-08-16 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_remove_movie_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
